
export const dispatcherApi = {
    url: 'https://conveyantdashadapter.azurewebsites.net/',
    auth: 'Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJjdXN0b21lciI6IkdhdGVrZWVwZXIgUGx1cmFsc2lnaHQiLCJ0eXBlIjoiZGVtbyIsImV4cGlyZXNPbiI6IjIwMzAtMTItMzEiLCJzZXJpYWwiOm51bGwsInBob25lcyI6MCwiYmVhY29ucyI6MTAsImVzY2FsYXRpb24iOmZhbHNlLCJjYWxsU2VydmVycyI6MSwib2ZmaG9vayI6ZmFsc2UsIm5vdGlmaWNhdGlvbkRvbWFpbnMiOjIsImhhIjowLCJkaXNwYXRjaGVyU2VyaWFsIjpudWxsLCJlbmRwb2ludHMiOiIxMDAwMDAwMDAwIiwiZGlzcGF0Y2hlckhhIjowLCJpYXQiOjE0OTQ1MTg1ODQsImlzcyI6IkNvbnZleWFudCBTeXN0ZW1zLCBJbmMuIiwic3ViIjoicGx1cmFsc2lnaHQifQ.TWw2Rm03pjz-0yXwyFXOMZeh-JP2lwJj6Zpn4f7i46tvffSRSRZIZ19IDn1rrv34C3rSEcquMBqhjagP6TjxxnrVLiPh72smEG0ER6xjK6Ux9qZDJMQ1MlOg-CzJDJI8H6sjpEapxtb1-JtciokS7M07WR_X71_eln84Da8osWhOXGNgQQa1G07kWPr0KNvTPmHbGoVIrHL_SAc-BKDwzQVUmmbZUvusfsQ5cKu6G1BO_PYToBW9f_BkqyEYJ11a1tZEI8JHgtoBWkzE0_DAgIkh9VZVksBpyuP28pdEXEmFWRzXsG5sUU_WIL7rmP-RRaxVCMmS4DdJuWXYIOxwyg',
};

export const app = {
  title: 'Sentry Dispatcher'
};
